var centrosFuncionais = {
    "AJU IT MT":"após a conclusão da atividade",
    "BHE CA AT":"após a conclusão da atividade",
    "BHE ES AT":"após a conclusão da atividade",
    "BHE ES GR": "após a conclusão da atividade",
    "BHE ES MD":"após a conclusão da atividade",
    "BHE ES MT":"após a conclusão da atividade",
    "BHE ES RD":"após a conclusão da atividade",
    "BLM GR MT":"após a conclusão da atividade",
    "BLM QB AT":"após a conclusão da atividade",
    "BLM QB FO":"após a conclusão da atividade",
    "BLM QB MT":"após a conclusão da atividade",
    "BNU AB AT":"após a conclusão da atividade",
    "BNU AB MT":"após a conclusão da atividade",
    "BR LIC GR": "antes de enviar para agendamento",
    "BRE AG AT":"após a conclusão da atividade",
    "BRE AG MD":"após a conclusão da atividade",
    "BRE AG MT":"após a conclusão da atividade",
    "BRU AL AT":"após a conclusão da atividade",
    "BRU AL MT":"após a conclusão da atividade",
    "BRU AL RD":"após a conclusão da atividade",
    "BSA SU FO":"antes de enviar para agendamento",
    "BSA SU MT":"antes de enviar para agendamento",
    "BVA AB AT":"após a conclusão da atividade",
    "BVA AB MD":"após a conclusão da atividade",
    "BVA AB MT":"após a conclusão da atividade",
    "BVA AB ST":"após a conclusão da atividade",
    "CAS BC AT":"após a conclusão da atividade",
    "CAS BC GR": "antes de enviar para agendamento",
    "CAS BC MD":"após a conclusão da atividade",
    "CAS BC MT":"após a conclusão da atividade",
    "CAS BC RD":"após a conclusão da atividade",
    "CAS VP MT":"após a conclusão da atividade",
    "CBA MC MD":"antes de enviar para agendamento",
    "CBA MC MT":"antes de enviar para agendamento",
    "CCO JL AT":"após a conclusão da atividade",
    "CMA FM MT":"após a conclusão da atividade",
    "CPE CM MD":"após a conclusão da atividade",
    "CPE CM MT":"após a conclusão da atividade",
    "CPS CL MT":"após a conclusão da atividade",
    "CSC DC AT":"após a conclusão da atividade",
    "CSC DC MT":"após a conclusão da atividade",
    "CSL VS MT":"após a conclusão da atividade",
    "CTA ACEFO":"após a conclusão da atividade",
    "CTA IMPMT":"após a conclusão da atividade",
    "CTA JR AT":"após a conclusão da atividade",
    "CTA MC AT":"após a conclusão da atividade",
    "CTA MC MT":"após a conclusão da atividade",
    "CTA MR AT":"após a conclusão da atividade",
    "CTA MR FO":"após a conclusão da atividade",
    "CTA MR MT":"após a conclusão da atividade",
    "CTA TF AT":"após a conclusão da atividade",
    "CTA TF MT":"após a conclusão da atividade",
    "CUA SV AT":"após a conclusão da atividade",
    "DOS CS MT":"após a conclusão da atividade",
    "FLA PV AT":"após a conclusão da atividade",
    "FLA PV MD":"após a conclusão da atividade",
    "FLA PV MT":"após a conclusão da atividade",
    "FNS ACEFO":"após a conclusão da atividade",
    "FNS IMPMT":"após a conclusão da atividade",
    "FNS PO AT":"após a conclusão da atividade",
    "FNS PO FO":"após a conclusão da atividade",
    "FNS PO MD":"após a conclusão da atividade",
    "FNS PO MT":"após a conclusão da atividade",
    "FOZ AI AT":"após a conclusão da atividade",
    "FOZ AI MT":"após a conclusão da atividade",
    "FSA GV MT":"após a conclusão da atividade",
    "GNA GR MT": "antes de enviar para agendamento",
    "GNA RD FO": "antes de enviar para agendamento",
    "GNA RD MT": "antes de enviar para agendamento",
    "GTBXGS MT":"após a conclusão da atividade",
    "GTBXGS ST":"após a conclusão da atividade",
    "GUR BR MT":"após a conclusão da atividade",
    "GVS JK MT":"após a conclusão da atividade",
    "IAI GM AT":"após a conclusão da atividade",
    "ILH AP MT":"após a conclusão da atividade",
    "ITZ RC AT":"após a conclusão da atividade",
    "ITZ RC MT":"após a conclusão da atividade",
    "JFA JC AT":"após a conclusão da atividade",
    "JFA JC MT":"após a conclusão da atividade",
    "JIP PV MT":"após a conclusão da atividade",
    "JNE JP MT":"após a conclusão da atividade",
    "JPA TR MT":"após a conclusão da atividade",
    "JVE LN AT":"após a conclusão da atividade",
    "JVE LN MT":"após a conclusão da atividade",
    "LDA PR AT":"após a conclusão da atividade",
    "LDA PR MT":"após a conclusão da atividade",
    "LGS CC AT":"após a conclusão da atividade",
    "LGS CC MT":"após a conclusão da atividade",
    "MBA QE MT":"após a conclusão da atividade",
    "MCO MS MT":"após a conclusão da atividade",
    "MGA NM AT":"após a conclusão da atividade",
    "MGA NM MT":"após a conclusão da atividade",
    "MNS EM MT":"após a conclusão da atividade",
    "MNS LM AT":"após a conclusão da atividade",
    "MNS LM MD":"após a conclusão da atividade",
    "MNS LM MT":"após a conclusão da atividade",
    "MNS LM ST":"após a conclusão da atividade",
    "MOSQST ST":"após a conclusão da atividade",
    "MPA GG AT":"após a conclusão da atividade",
    "MPA GG MT":"após a conclusão da atividade",
    "NHO LO MT":"após a conclusão da atividade",
    "NTL JU AT":"após a conclusão da atividade",
    "NTL JU MD":"após a conclusão da atividade",
    "NTL JU MT":"após a conclusão da atividade",
    "OCO SA AT":"após a conclusão da atividade",
    "OCO SA MT":"após a conclusão da atividade",
    "PAE BV AT":"após a conclusão da atividade",
    "PAE BV MD":"após a conclusão da atividade",
    "PAE BV MT":"após a conclusão da atividade",
    "PAE BV RD":"após a conclusão da atividade",
    "PAE DESAT":"após a conclusão da atividade",
    "PAE GA AT":"após a conclusão da atividade",
    "PAE IMPAT":"após a conclusão da atividade",
    "PAE IMPMT":"após a conclusão da atividade",
    "PAE LX MT":"após a conclusão da atividade",
    "PAE MF MD":"após a conclusão da atividade",
    "PAE MF MT":"após a conclusão da atividade",
    "PAS CC MT":"após a conclusão da atividade",
    "PGO RB AT":"após a conclusão da atividade",
    "PGO RB MT":"após a conclusão da atividade",
    "PGU BR MT":"após a conclusão da atividade",
    "PLT QN MT":"após a conclusão da atividade",
    "PMJ SO FO":"antes de enviar para agendamento",
    "PMJ SO MT":"antes de enviar para agendamento",
    "PNG GL AT":"após a conclusão da atividade",
    "PPE CM AT":"após a conclusão da atividade",
    "PPE CM MT":"após a conclusão da atividade",
    "PPE CM RD":"após a conclusão da atividade",
    "PTA PL MT":"após a conclusão da atividade",
    "PVO FQ MD":"após a conclusão da atividade",
    "PVO FQ MT":"após a conclusão da atividade",
    "RBO RB MD":"após a conclusão da atividade",
    "RBO RB MT":"após a conclusão da atividade",
    "RCE AM AT":"após a conclusão da atividade",
    "RCE AM MT":"após a conclusão da atividade",
    "RJO AC MT":"antes de enviar para agendamento",
    "RJO AM AT":"antes de enviar para agendamento",
    "RJO AM MD":"antes de enviar para agendamento",
    "RJO AM MT":"antes de enviar para agendamento",
    "RJO CO MT":"antes de enviar para agendamento",
    "RJO DD GR": "antes de enviar para agendamento",
    "RJO EN MT":"antes de enviar para agendamento",
    "ROI MD RD":"após a conclusão da atividade",
    "RPO TB AT":"após a conclusão da atividade",
    "RPO TB MT":"após a conclusão da atividade",
    "RPO TB RD":"após a conclusão da atividade",
    "SAN AN MT":"após a conclusão da atividade",
    "SCR EA MT":"após a conclusão da atividade",
    "SDR IT MT":"após a conclusão da atividade",
    "SDR RC MD":"após a conclusão da atividade",
    "SDR RC MT":"após a conclusão da atividade",
    "SJC EB AT":"após a conclusão da atividade",
    "SJC EB MT":"após a conclusão da atividade",
    "SLS US AT":"após a conclusão da atividade",
    "SLS US MD":"após a conclusão da atividade",
    "SLS US MT":"após a conclusão da atividade",
    "SMA AN MT":"após a conclusão da atividade",
    "SNE JC AT":"após a conclusão da atividade",
    "SNE JC FB":"após a conclusão da atividade",
    "SNE JC FO":"após a conclusão da atividade",
    "SNE JC MT":"após a conclusão da atividade",
    "SOC PH AT":"após a conclusão da atividade",
    "SOC PH MT":"após a conclusão da atividade",
    "SOC PH RD":"após a conclusão da atividade",

    "SPO ADM45":"após a conclusão da atividade",
    "SPO ADMGR":"após a conclusão da atividade",
    "SPO ADMMT":"após a conclusão da atividade",
    "SPO BG AT":"após a conclusão da atividade",
    "SPO DD GR": "antes de enviar para agendamento",
    "SPO EI AT":"após a conclusão da atividade",
    "SPO EI MT":"antes de enviar para agendamento",
    "SPO IG 45":"após a conclusão da atividade",
    "SPO IG AT":"após a conclusão da atividade",
    "SPO IG FO":"após a conclusão da atividade",
    "SPO IG GR": "antes de enviar para agendamento",
    "SPO IG MD":"antes de enviar para agendamento",
    "SPO IG MT":"antes de enviar para agendamento",
    "SPO LP AT":"após a conclusão da atividade",
    "SPO LP MD":"antes de enviar para agendamento",
    "SPO LP MT":"antes de enviar para agendamento",
    "SPO MB AT":"após a conclusão da atividade",
    "SPO MB MD":"antes de enviar para agendamento",
    "SPO MB MT":"antes de enviar para agendamento",
    "SPO PH AT":"após a conclusão da atividade",
    "SPO PH MD":"antes de enviar para agendamento",
    "SPO PH MT":"antes de enviar para agendamento",
    "SPO PPCMD":"antes de enviar para agendamento",
    "SPO VE MT":"antes de enviar para agendamento",

    "SRM SP MT":"após a conclusão da atividade",
    "SRR QN AT":"após a conclusão da atividade",
    "SRR QN MT":"após a conclusão da atividade",
    "SRR QN RD":"após a conclusão da atividade",
    "STS WL AT":"após a conclusão da atividade",
    "STS WL MD":"após a conclusão da atividade",
    "STS WL MT":"após a conclusão da atividade",
    "STS WL RD":"após a conclusão da atividade",
    "TANGBR MT":"após a conclusão da atividade",
    "TLS ES MT":"após a conclusão da atividade",
    "TSA AN AT":"após a conclusão da atividade",
    "TSA AN MT":"após a conclusão da atividade",
    "TTE SC MT":"após a conclusão da atividade",
    "UGN QN MT":"após a conclusão da atividade",
    "ULA MA AT":"após a conclusão da atividade",
    "ULA MA MT":"após a conclusão da atividade",
    "URA FR MT":"após a conclusão da atividade",
    "VCA TN MT":"após a conclusão da atividade",
    "VGA TG MD":"após a conclusão da atividade",
    "VGA TG MT":"após a conclusão da atividade",
    "VRD SC MT":"antes de enviar para agendamento",
    "VTA JM AT":"após a conclusão da atividade",
    "VTA JM MD":"após a conclusão da atividade",
    "VTA JM MT":"após a conclusão da atividade"
};

function buscarEstacao() {
var sigla = document.getElementById("sigla").value.toUpperCase().trim(); // Obtém a sigla inserida pelo usuário em letras maiúsculas
var estacaoLabel = document.getElementById("resultado"); // Obtém o elemento HTML onde será exibido o resultado

// Verifica se a sigla existe no dicionário
if (centrosFuncionais.hasOwnProperty(sigla)) {
var estacao = centrosFuncionais[sigla]; // Obtém o nome da estação correspondente à sigla
estacaoLabel.textContent = "Será executado " + estacao; // Exibe o resultado no elemento HTML
} else {
estacaoLabel.textContent = "Sigla não encontrada"; // Exibe mensagem de erro caso a sigla não seja encontrada
}
}

function limparDados() {
document.getElementById("sigla").value = ""; // Limpa o campo de input
document.getElementById("resultado").textContent = ""; // Limpa o resultado anterior
}

document.getElementById("sigla").addEventListener("keydown", function(event) {
if (event.key === "Enter") {
event.preventDefault(); // Impede o comportamento padrão do Enter de inserir uma quebra de linha
buscarEstacao();
}
});

document.addEventListener("keydown", function(event) {
if (event.key === "Escape") {
event.preventDefault(); // Impede o comportamento padrão do ESC de fechar a janela
limparDados();
}
});
