var centrosFuncionais = {
    "AJU IT MT":"",
    "BHE CA AT":"",
    "BHE ES AT":"",
    "BHE ES GR":"",
    "BHE ES MD":"",
    "BHE ES MT":"",
    "BHE ES RD":"",
    "BLM GR MT":"",
    "BLM QB AT":"",
    "BLM QB FO":"",
    "BLM QB MT":"",
    "BNU AB AT":"",
    "BNU AB MT":"",
    "BR LIC GR":"",
    "BRE AG AT":"",
    "BRE AG MD":"",
    "BRE AG MT":"",
    "BRU AL AT":"",
    "BRU AL MT":"",
    "BRU AL RD":"",
    "BSA SU FO":"",
    "BSA SU MT":"",
    "BVA AB AT":"",
    "BVA AB MD":"",
    "BVA AB MT":"",
    "BVA AB ST":"",
    "CAS BC AT":"",
    "CAS BC GR":"",
    "CAS BC MD":"",
    "CAS BC MT":"",
    "CAS BC RD":"",
    "CAS VP MT":"",
    "CBA MC MD":"",
    "CBA MC MT":"",
    "CCO JL AT":"",
    "CMA FM MT":"",
    "CPE CM MD":"",
    "CPE CM MT":"",
    "CPS CL MT":"",
    "CSC DC AT":"",
    "CSC DC MT":"",
    "CSL VS MT":"",
    "CTA ACEFO":"",
    "CTA IMPMT":"",
    "CTA JR AT":"",
    "CTA MC AT":"",
    "CTA MC MT":"",
    "CTA MR AT":"",
    "CTA MR FO":"",
    "CTA MR MT":"",
    "CTA TF AT":"",
    "CTA TF MT":"",
    "CUA SV AT":"",
    "DOS CS MT":"",
    "FLA PV AT":"",
    "FLA PV MD":"",
    "FLA PV MT":"",
    "FNS ACEFO":"",
    "FNS IMPMT":"",
    "FNS PO AT":"",
    "FNS PO FO":"",
    "FNS PO MD":"",
    "FNS PO MT":"",
    "FOZ AI AT":"",
    "FOZ AI MT":"",
    "FSA GV MT":"",
    "GNA GR MT":"",
    "GNA RD FO":"",
    "GNA RD MT":"",
    "GTBXGS MT":"",
    "GTBXGS ST":"",
    "GUR BR MT":"",
    "GVS JK MT":"",
    "IAI GM AT":"",
    "ILH AP MT":"",
    "ITZ RC AT":"",
    "ITZ RC MT":"",
    "JFA JC AT":"",
    "JFA JC MT":"",
    "JIP PV MT":"",
    "JNE JP MT":"",
    "JPA TR MT":"",
    "JVE LN AT":"",
    "JVE LN MT":"",
    "LDA PR AT":"",
    "LDA PR MT":"",
    "LGS CC AT":"",
    "LGS CC MT":"",
    "MBA QE MT":"",
    "MCO MS MT":"",
    "MGA NM AT":"",
    "MGA NM MT":"",
    "MNS EM MT":"",
    "MNS LM AT":"",
    "MNS LM MD":"",
    "MNS LM MT":"",
    "MNS LM ST":"",
    "MOSQST ST":"",
    "MPA GG AT":"",
    "MPA GG MT":"",
    "NHO LO MT":"",
    "NTL JU AT":"",
    "NTL JU MD":"",
    "NTL JU MT":"",
    "OCO SA AT":"",
    "OCO SA MT":"",
    "PAE BV AT":"",
    "PAE BV MD":"",
    "PAE BV MT":"",
    "PAE BV RD":"",
    "PAE DESAT":"",
    "PAE GA AT":"",
    "PAE IMPAT":"",
    "PAE IMPMT":"",
    "PAE LX MT":"",
    "PAE MF MD":"",
    "PAE MF MT":"",
    "PAS CC MT":"",
    "PGO RB AT":"",
    "PGO RB MT":"",
    "PGU BR MT":"",
    "PLT QN MT":"",
    "PMJ SO FO":"",
    "PMJ SO MT":"",
    "PNG GL AT":"",
    "PPE CM AT":"",
    "PPE CM MT":"",
    "PPE CM RD":"",
    "PTA PL MT":"",
    "PVO FQ MD":"",
    "PVO FQ MT":"",
    "RBO RB MD":"",
    "RBO RB MT":"",
    "RCE AM AT":"",
    "RCE AM MT":"",
    "RJO AC MT":"",
    "RJO AM AT":"",
    "RJO AM MD":"",
    "RJO AM MT":"",
    "RJO CO MT":"",
    "RJO DD GR":"",
    "RJO EN MT":"",
    "ROI MD RD":"",
    "RPO TB AT":"",
    "RPO TB MT":"",
    "RPO TB RD":"",
    "SAN AN MT":"",
    "SCR EA MT":"",
    "SDR IT MT":"",
    "SDR RC MD":"",
    "SDR RC MT":"",
    "SJC EB AT":"",
    "SJC EB MT":"",
    "SLS US AT":"",
    "SLS US MD":"",
    "SLS US MT":"",
    "SMA AN MT":"",
    "SNE JC AT":"",
    "SNE JC FB":"",
    "SNE JC FO":"",
    "SNE JC MT":"",
    "SOC PH AT":"",
    "SOC PH MT":"",
    "SOC PH RD":"",
    "SPO ADM45":"",
    "SPO ADMGR":"",
    "SPO ADMMT":"",
    "SPO BG AT":"",
    "SPO DD GR":"",
    "SPO EI AT":"",
    "SPO EI MT":"",
    "SPO IG 45":"",
    "SPO IG AT":"",
    "SPO IG FO":"",
    "SPO IG GR":"",
    "SPO IG MD":"",
    "SPO IG MT":"",
    "SPO LP AT":"",
    "SPO LP MD":"",
    "SPO LP MT":"",
    "SPO MB AT":"",
    "SPO MB MD":"",
    "SPO MB MT":"",
    "SPO PH AT":"",
    "SPO PH MD":"",
    "SPO PH MT":"",
    "SPO PPCMD":"",
    "SPO VE MT":"",
    "SRM SP MT":"",
    "SRR QN AT":"",
    "SRR QN MT":"",
    "SRR QN RD":"",
    "STS WL AT":"",
    "STS WL MD":"",
    "STS WL MT":"",
    "STS WL RD":"",
    "TANGBR MT":"",
    "TLS ES MT":"",
    "TSA AN AT":"",
    "TSA AN MT":"",
    "TTE SC MT":"",
    "UGN QN MT":"",
    "ULA MA AT":"",
    "ULA MA MT":"",
    "URA FR MT":"",
    "VCA TN MT":"",
    "VGA TG MD":"",
    "VGA TG MT":"",
    "VRD SC MT":"",
    "VTA JM AT":"",
    "VTA JM MD":"",
    "VTA JM MT":"",

    "BLM QB MT": "após conclusão da atividade.",
    "BHE ES MT": "após conclusão da atividade.",
    "BRU AL AT": "após conclusão da atividade.",
    "RPO TB AT": "após conclusão da atividade.",
    "BRU AL MT": "após conclusão da atividade.",
    "BHE ES AT": "após conclusão da atividade.",
    "GVS JK MT": "após conclusão da atividade.",
    "JFA JC MT": "após conclusão da atividade.",
    "CAS BC AT": "após conclusão da atividade.",
    "SJC EB AT": "após conclusão da atividade.",
    "SOC PH AT": "após conclusão da atividade.",
    "ULA MA MT": "após conclusão da atividade.",
    "URA FR MT": "após conclusão da atividade.",
    "RPO TB AT": "após conclusão da atividade.",
    "SJC EB MT": "após conclusão da atividade.",
    "PPE CM MT": "após conclusão da atividade.",
    "SJC EB MD": "após conclusão da atividade.",
    "SRR QN MT": "após conclusão da atividade.",
    "RPO TB MT": "após conclusão da atividade.",
    "MNS EM MT": "após conclusão da atividade.",
    "MNS LM MD": "após conclusão da atividade.",
    "RJO AM MT": "em conjunto com a atividade.",
    "VGA TG MT": "em conjunto com a atividade.",
    "SRR QN AT": "em conjunto com a atividade."
    // Adicionar todas as siglas e estações aqui
    };

function buscarEstacao() {
var sigla = document.getElementById("sigla").value.toUpperCase().trim(); // Obtém a sigla inserida pelo usuário em letras maiúsculas
var estacaoLabel = document.getElementById("resultado"); // Obtém o elemento HTML onde será exibido o resultado

// Verifica se a sigla existe no dicionário
if (centrosFuncionais.hasOwnProperty(sigla)) {
var estacao = centrosFuncionais[sigla]; // Obtém o nome da estação correspondente à sigla
estacaoLabel.textContent = "Será executado " + estacao; // Exibe o resultado no elemento HTML
} else {
estacaoLabel.textContent = "Sigla não encontrada"; // Exibe mensagem de erro caso a sigla não seja encontrada
}
}

function limparDados() {
document.getElementById("sigla").value = ""; // Limpa o campo de input
document.getElementById("resultado").textContent = ""; // Limpa o resultado anterior
}

document.getElementById("sigla").addEventListener("keydown", function(event) {
if (event.key === "Enter") {
event.preventDefault(); // Impede o comportamento padrão do Enter de inserir uma quebra de linha
buscarEstacao();
}
});

document.addEventListener("keydown", function(event) {
if (event.key === "Escape") {
event.preventDefault(); // Impede o comportamento padrão do ESC de fechar a janela
limparDados();
}
});
