var centrosFuncionais = {
    "AJU IT MT":"",
    "BHE CA AT":"após a conclusão da atividade",
    "BHE ES AT":"após a conclusão da atividade",
    "BHE ES GR": "antes de enviar para agendamento",
    "BHE ES MD":"antes de enviar para agendamento",
    "BHE ES MT":"antes de enviar para agendamento",
    "BHE ES RD":"",
    "BLM GR MT":"após a conclusão da atividade",
    "BLM QB AT":"após a conclusão da atividade",
    "BLM QB FO":"após a conclusão da atividade",
    "BLM QB MT":"após a conclusão da atividade",
    "BNU AB AT":"após a conclusão da atividade",
    "BNU AB MT":"",
    "BR LIC GR": "antes de enviar para agendamento",
    "BRE AG AT":"após a conclusão da atividade",
    "BRE AG MD":"",
    "BRE AG MT":"",
    "BRU AL AT":"após a conclusão da atividade",
    "BRU AL MT":"após a conclusão da atividade",
    "BRU AL RD":"antes de enviar para agendamento",
    "BSA SU FO":"antes de enviar para agendamento",
    "BSA SU MT":"antes de enviar para agendamento",
    "BVA AB AT":"após a conclusão da atividade",
    "BVA AB MD":"",
    "BVA AB MT":"",
    "BVA AB ST":"",
    "CAS BC AT":"após a conclusão da atividade",
    "CAS BC GR": "antes de enviar para agendamento",
    "CAS BC MD":"",
    "CAS BC MT":"",
    "CAS BC RD":"",
    "CAS VP MT":"",
    "CBA MC MD":"",
    "CBA MC MT":"",
    "CCO JL AT":"após a conclusão da atividade",
    "CMA FM MT":"",
    "CPE CM MD":"",
    "CPE CM MT":"",
    "CPS CL MT":"",
    "CSC DC AT":"após a conclusão da atividade",
    "CSC DC MT":"",
    "CSL VS MT":"",
    "CTA ACEFO":"",
    "CTA IMPMT":"",
    "CTA JR AT":"após a conclusão da atividade",
    "CTA MC AT":"após a conclusão da atividade",
    "CTA MC MT":"",
    "CTA MR AT":"após a conclusão da atividade",
    "CTA MR FO":"",
    "CTA MR MT":"",
    "CTA TF AT":"após a conclusão da atividade",
    "CTA TF MT":"",
    "CUA SV AT":"após a conclusão da atividade",
    "DOS CS MT":"",
    "FLA PV AT":"após a conclusão da atividade",
    "FLA PV MD":"",
    "FLA PV MT":"",
    "FNS ACEFO":"",
    "FNS IMPMT":"",
    "FNS PO AT":"após a conclusão da atividade",
    "FNS PO FO":"",
    "FNS PO MD":"",
    "FNS PO MT":"",
    "FOZ AI AT":"após a conclusão da atividade",
    "FOZ AI MT":"",
    "FSA GV MT":"",
    "GNA GR MT": "antes de enviar para agendamento",
    "GNA RD FO": "antes de enviar para agendamento",
    "GNA RD MT": "antes de enviar para agendamento",
    "GTBXGS MT":"",
    "GTBXGS ST":"",
    "GUR BR MT":"",
    "GVS JK MT":"",
    "IAI GM AT":"após a conclusão da atividade",
    "ILH AP MT":"",
    "ITZ RC AT":"após a conclusão da atividade",
    "ITZ RC MT":"",
    "JFA JC AT":"após a conclusão da atividade",
    "JFA JC MT":"",
    "JIP PV MT":"",
    "JNE JP MT":"",
    "JPA TR MT":"",
    "JVE LN AT":"após a conclusão da atividade",
    "JVE LN MT":"",
    "LDA PR AT":"após a conclusão da atividade",
    "LDA PR MT":"",
    "LGS CC AT":"após a conclusão da atividade",
    "LGS CC MT":"",
    "MBA QE MT":"",
    "MCO MS MT":"",
    "MGA NM AT":"após a conclusão da atividade",
    "MGA NM MT":"",
    "MNS EM MT":"",
    "MNS LM AT":"após a conclusão da atividade",
    "MNS LM MD":"",
    "MNS LM MT":"",
    "MNS LM ST":"",
    "MOSQST ST":"",
    "MPA GG AT":"após a conclusão da atividade",
    "MPA GG MT":"",
    "NHO LO MT":"",
    "NTL JU AT":"após a conclusão da atividade",
    "NTL JU MD":"",
    "NTL JU MT":"",
    "OCO SA AT":"após a conclusão da atividade",
    "OCO SA MT":"",
    "PAE BV AT":"após a conclusão da atividade",
    "PAE BV MD":"",
    "PAE BV MT":"",
    "PAE BV RD":"",
    "PAE DESAT":"",
    "PAE GA AT":"após a conclusão da atividade",
    "PAE IMPAT":"após a conclusão da atividade",
    "PAE IMPMT":"",
    "PAE LX MT":"",
    "PAE MF MD":"",
    "PAE MF MT":"",
    "PAS CC MT":"",
    "PGO RB AT":"após a conclusão da atividade",
    "PGO RB MT":"",
    "PGU BR MT":"",
    "PLT QN MT":"",
    "PMJ SO FO":"",
    "PMJ SO MT":"",
    "PNG GL AT":"após a conclusão da atividade",
    "PPE CM AT":"após a conclusão da atividade",
    "PPE CM MT":"",
    "PPE CM RD":"",
    "PTA PL MT":"",
    "PVO FQ MD":"",
    "PVO FQ MT":"",
    "RBO RB MD":"",
    "RBO RB MT":"",
    "RCE AM AT":"após a conclusão da atividade",
    "RCE AM MT":"",
    "RJO AC MT":"",
    "RJO AM AT":"após a conclusão da atividade",
    "RJO AM MD":"",
    "RJO AM MT":"",
    "RJO CO MT":"",
    "RJO DD GR": "antes de enviar para agendamento",
    "RJO EN MT":"",
    "ROI MD RD":"",
    "RPO TB AT":"após a conclusão da atividade",
    "RPO TB MT":"",
    "RPO TB RD":"",
    "SAN AN MT":"",
    "SCR EA MT":"",
    "SDR IT MT":"",
    "SDR RC MD":"",
    "SDR RC MT":"",
    "SJC EB AT":"após a conclusão da atividade",
    "SJC EB MT":"",
    "SLS US AT":"após a conclusão da atividade",
    "SLS US MD":"",
    "SLS US MT":"",
    "SMA AN MT":"",
    "SNE JC AT":"após a conclusão da atividade",
    "SNE JC FB":"",
    "SNE JC FO":"",
    "SNE JC MT":"",
    "SOC PH AT":"após a conclusão da atividade",
    "SOC PH MT":"",
    "SOC PH RD":"",

    "SPO ADM45":"",
    "SPO ADMGR":"",
    "SPO ADMMT":"",
    "SPO BG AT":"após a conclusão da atividade",
    "SPO DD GR": "antes de enviar para agendamento",
    "SPO EI AT":"após a conclusão da atividade",
    "SPO EI MT":"antes de enviar para agendamento",
    "SPO IG 45":"",
    "SPO IG AT":"após a conclusão da atividade",
    "SPO IG FO":"",
    "SPO IG GR": "antes de enviar para agendamento",
    "SPO IG MD":"antes de enviar para agendamento",
    "SPO IG MT":"antes de enviar para agendamento",
    "SPO LP AT":"após a conclusão da atividade",
    "SPO LP MD":"antes de enviar para agendamento",
    "SPO LP MT":"antes de enviar para agendamento",
    "SPO MB AT":"após a conclusão da atividade",
    "SPO MB MD":"antes de enviar para agendamento",
    "SPO MB MT":"antes de enviar para agendamento",
    "SPO PH AT":"após a conclusão da atividade",
    "SPO PH MD":"antes de enviar para agendamento",
    "SPO PH MT":"antes de enviar para agendamento",
    "SPO PPCMD":"antes de enviar para agendamento",
    "SPO VE MT":"antes de enviar para agendamento",

    "SRM SP MT":"",
    "SRR QN AT":"após a conclusão da atividade",
    "SRR QN MT":"",
    "SRR QN RD":"",
    "STS WL AT":"após a conclusão da atividade",
    "STS WL MD":"",
    "STS WL MT":"",
    "STS WL RD":"",
    "TANGBR MT":"",
    "TLS ES MT":"",
    "TSA AN AT":"após a conclusão da atividade",
    "TSA AN MT":"",
    "TTE SC MT":"",
    "UGN QN MT":"",
    "ULA MA AT":"após a conclusão da atividade",
    "ULA MA MT":"",
    "URA FR MT":"",
    "VCA TN MT":"",
    "VGA TG MD":"",
    "VGA TG MT":"",
    "VRD SC MT":"",
    "VTA JM AT":"após a conclusão da atividade",
    "VTA JM MD":"",
    "VTA JM MT":"",

    "BLM QB MT": "após conclusão da atividade.",
    "BHE ES MT": "após conclusão da atividade.",
    "BRU AL AT": "após conclusão da atividade.",
    "RPO TB AT": "após conclusão da atividade.",
    "BRU AL MT": "após conclusão da atividade.",
    "BHE ES AT": "após conclusão da atividade.",
    "GVS JK MT": "após conclusão da atividade.",
    "JFA JC MT": "após conclusão da atividade.",
    "CAS BC AT": "após conclusão da atividade.",
    "SJC EB AT": "após conclusão da atividade.",
    "SOC PH AT": "após conclusão da atividade.",
    "ULA MA MT": "após conclusão da atividade.",
    "URA FR MT": "após conclusão da atividade.",
    "RPO TB AT": "após conclusão da atividade.",
    "SJC EB MT": "após conclusão da atividade.",
    "PPE CM MT": "após conclusão da atividade.",
    "SJC EB MD": "após conclusão da atividade.",
    "SRR QN MT": "após conclusão da atividade.",
    "RPO TB MT": "após conclusão da atividade.",
    "MNS EM MT": "após conclusão da atividade.",
    "MNS LM MD": "após conclusão da atividade.",
    "RJO AM MT": "em conjunto com a atividade.",
    "VGA TG MT": "em conjunto com a atividade.",
    "SRR QN AT": "em conjunto com a atividade."
    // Adicionar todas as siglas e estações aqui
    };

function buscarEstacao() {
var sigla = document.getElementById("sigla").value.toUpperCase().trim(); // Obtém a sigla inserida pelo usuário em letras maiúsculas
var estacaoLabel = document.getElementById("resultado"); // Obtém o elemento HTML onde será exibido o resultado

// Verifica se a sigla existe no dicionário
if (centrosFuncionais.hasOwnProperty(sigla)) {
var estacao = centrosFuncionais[sigla]; // Obtém o nome da estação correspondente à sigla
estacaoLabel.textContent = "Será executado " + estacao; // Exibe o resultado no elemento HTML
} else {
estacaoLabel.textContent = "Sigla não encontrada"; // Exibe mensagem de erro caso a sigla não seja encontrada
}
}

function limparDados() {
document.getElementById("sigla").value = ""; // Limpa o campo de input
document.getElementById("resultado").textContent = ""; // Limpa o resultado anterior
}

document.getElementById("sigla").addEventListener("keydown", function(event) {
if (event.key === "Enter") {
event.preventDefault(); // Impede o comportamento padrão do Enter de inserir uma quebra de linha
buscarEstacao();
}
});

document.addEventListener("keydown", function(event) {
if (event.key === "Escape") {
event.preventDefault(); // Impede o comportamento padrão do ESC de fechar a janela
limparDados();
}
});
